name: Build and Deploy Jekyll (Stable Image)

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Jekyll site with stable Ruby image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/site:/srv/jekyll \
            -v ${{ github.workspace }}/site/_site:/srv/jekyll/_site \
            ruby:3.2-bullseye /bin/bash -c "
              apt-get update &&
              apt-get install -y build-essential nodejs npm git &&
              gem install bundler jekyll ffi &&
              cd /srv/jekyll &&
              bundle config set path 'vendor/bundle' &&
              bundle install &&
              bundle exec jekyll build --future
            "

      - name: Deploy to test branch (gh-pages-test)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/_site
          publish_branch: gh-pages-test
          commit_message: '🧪 Test build with stable Ruby image'
