name: Build Jekyll site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd site
          bundle install

      - name: Build Jekyll site
        run: |
          cd site
          bundle exec jekyll build --future
