name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Jekyll site (in site folder)
        run: |
          docker run \
            -v ${{ github.workspace }}/site:/srv/jekyll \
            -v ${{ github.workspace }}/site/_site:/srv/jekyll/_site \
            jekyll/builder:latest /bin/bash -c "
              chmod -R 777 /srv/jekyll &&
              gem install jekyll-bookshop &&
              bundle install &&
              jekyll build --future
            "
