name: Build and Deploy Jekyll (Test with Bookshop Assets)

on:
  push:
    branches: [ "main" ]  # or your default branch

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Ruby for Jekyll
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      # Install Node for Bookshop + npm build tools
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd site
          bundle install
          npm install

      - name: Build Bookshop components
        run: |
          cd site
          npx @cloudcannon/bookshop build

      - name: Build Jekyll site
        run: |
          cd site
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy to test branch (gh-pages-test)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/_site
          publish_branch: gh-pages-test
          commit_message: "🧪 Test build with Bookshop assets"
